### ISSUE TITLE
Use babel's sourceRoot option instead of sourceDir

### ISSUE THREAD

**Issue by per2plex** [per2plex/babel-project-relative-import#12]
Babel's native sourceRoot option could be used instead of the plugins sourceDir, but this requires a major rewrite. This would also cleanup some confusing path joining.

Check compatibility with other plugins beforehand.
Also see: https://github.com/per2plex/babel-project-relative-import/issues/8

**Comment by m59peacemaker** [comment]
If I got this right, no more worries about confusing path joining. :)

https://www.npmjs.com/package/root-import-utils

`getRelativePathToModule()` or `getLongRelativePathToModule()` will take care of it all!

**Comment by m59peacemaker** [comment]
Eh, not quite right yet.

**Comment by m59peacemaker** [comment]
I don't think `sourceRoot` does what I had in mind. It produces paths in the sourcemaps like `src/../src/etc`. I don't have any clue what that is useful for. Here's my plugin for requires.
https://github.com/m59peacemaker/babel-plugin-root-require

**Comment by per2plex** [comment]
So if I understand correctly, changing sourceRoot had an effect on the generated sourcemaps? Do you think it's not worth using this option?
