### ISSUE TITLE
Not working under Babel 6.14 with register-hook

### ISSUE THREAD

**Issue by JonathanRoyGagnon** [per2plex/babel-project-relative-import#13]
Hi,
The plugin is not working when used with babel 6.14 register-hook.

```
Error: Cannot find module './src/component/server'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

The call is in `[project]/src/component/auth/auth.middleware.test.js`

The plugin has been broken by the following merge : https://github.com/babel/babel/pull/3608/files
Discussion about the pull request : https://github.com/babel/babel/pull/3608

My .babelrc

```
{
  "presets": ["node6", "stage-0"],
  "plugins": [
    "transform-runtime",
    "babel-plugin-transform-decorators-legacy",
    [ "babel-project-relative-import" , { "sourceDir": "src" }]
  ]
}
```

Broken test example :

```
//.babelrc
{
  "presets": ["latest"],
  "plugins": [
    [ "babel-project-relative-import" , { "sourceDir": "a" }]
  ]
}

// main.js
require('babel-core/register');
require('./a/c/c.js');

// a/b/b.js
console.log('hello');

// a/c/c.js
import '~/b/b.js';

// package.json
{
  "name": "test",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-core": "^6.14.0",
    "babel-preset-latest": "^6.14.0",
    "babel-project-relative-import": "^2.0.0"
  },
  "engines": {
    "node": ">=6.3.0"
  },
  "private": true
}
```

Run `node main.js`

**Comment by per2plex** [comment]
Yeah, `sourceRoot` being set automatically to the `dirname` of the file breaks the current implementation. A temporary fix in your project would be settings `sourceRoot` to `process.cwd()` manually in whichever babel wrapper you use.

Or if you use the babel-cli directly: `babel --source-root $(pwd)`

I'll rewrite the plugin soon and the `sourceDir` option will be replaced by babel's `sourceRoot` option, so setting `sourceRoot` will be required anyway in the future (probably).

See: https://github.com/per2plex/babel-project-relative-import/issues/12

**Comment by JonathanRoyGagnon** [comment]
Thanks for the fast reply!
I'm eagerly waiting the new version ^^.
Just for information, setting source-root directly in the register-hook configuration doesn't seems to work as the new option is overridden by babel. It might be an overlook from the babel guys.

**Comment by per2plex** [comment]
Seems you were right (https://github.com/babel/babel/pull/3685). Thanks for notifying them about this issue. Does the temporary fix work now?

**Comment by JonathanRoyGagnon** [comment]
I haven't test yet. The latest revision (6.15) does not have the modification (it has been added after). I will give feedback as soon as the new babel revision is out.

**Comment by per2plex** [comment]
I released a beta version under the NPM tag `beta` which does not use babel's `sourceRoot` option anymore and replaces it with a custom `projectRoot` option which defaults to `process.cwd`, so in your case it should just work.

**Comment by JonathanRoyGagnon** [comment]
It now works under babel 6.16, I added this overwrite in my gulpfile :

```
require('babel-register')({
  sourceRoot: process.cwd()
});
```

Thanks for this plugging, it is the only one working exactly how I want it to ^^.
